/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Computador;
import Model.Bean.Setor;
import Model.Bean.User;
import Model.DAO.CadastroDAO;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro Melo
 * 
 * Esta tela está temporariamente desativada pois a logica foi imcorporada
 * na tela cadastro de patrimônio. Esta tela está aqui apenas para consulta
 * dos códigos. Em breve será extinta.
 * 
 */
public class CadastroComputador extends javax.swing.JInternalFrame {

    public CadastroComputador() {
        initComponents();
        
        CadastroDAO setores = new CadastroDAO();
        
        for(Setor s: setores.readSetor()){
            cbSetores.addItem(s);
        }
        
        CadastroDAO user = new CadastroDAO();
        
        user.readUser().forEach((u) -> {
            cbUserName.addItem(u);
        });
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_usuario = new javax.swing.JLabel();
        campo_hd = new javax.swing.JTextField();
        label_processador = new javax.swing.JLabel();
        campo_processador = new javax.swing.JTextField();
        label_setor = new javax.swing.JLabel();
        label_hd = new javax.swing.JLabel();
        label_memoria = new javax.swing.JLabel();
        campo_memoria = new javax.swing.JTextField();
        label_ssd = new javax.swing.JLabel();
        label_tombamento = new javax.swing.JLabel();
        campo_numTombamento = new javax.swing.JTextField();
        cbSetores = new javax.swing.JComboBox<>();
        cbSsd = new javax.swing.JCheckBox();
        cbUserName = new javax.swing.JComboBox<>();
        label_hd1 = new javax.swing.JLabel();
        label_hd2 = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botao_cadastrar = new javax.swing.JButton();
        botao_limpar = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CADASTRAR COMPUTADOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        label_usuario.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_usuario.setText("Usuário: ");

        campo_hd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campo_hd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_hdFocusGained(evt);
            }
        });
        campo_hd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_hdKeyPressed(evt);
            }
        });

        label_processador.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_processador.setText("Processador:");

        campo_processador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_processadorFocusGained(evt);
            }
        });
        campo_processador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_processadorKeyPressed(evt);
            }
        });

        label_setor.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_setor.setText("Setor:");

        label_hd.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_hd.setText("HD:");

        label_memoria.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_memoria.setText("Memória:");

        campo_memoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_memoriaFocusGained(evt);
            }
        });
        campo_memoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_memoriaKeyPressed(evt);
            }
        });

        label_ssd.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_ssd.setText("SSD:");

        label_tombamento.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_tombamento.setText("Nº Tombamento:");

        campo_numTombamento.setText("00000");
        campo_numTombamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_numTombamentoFocusGained(evt);
            }
        });
        campo_numTombamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_numTombamentoKeyPressed(evt);
            }
        });

        cbSsd.setText("SIM");

        label_hd1.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        label_hd1.setText("GB");

        label_hd2.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        label_hd2.setText("GB");
        label_hd2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campo_processador)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campo_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_hd2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_processador, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbUserName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_setor)
                                    .addComponent(cbSetores, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_tombamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campo_numTombamento)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSsd)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(label_hd)
                                    .addGap(105, 105, 105)
                                    .addComponent(label_ssd))))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_memoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(campo_hd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_hd1)))
                        .addGap(126, 534, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_usuario)
                    .addComponent(label_setor)
                    .addComponent(label_tombamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSetores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_numTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_processador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_processador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hd)
                    .addComponent(label_ssd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSsd)
                        .addComponent(label_hd1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campo_hd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_memoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_hd2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        label_titulo.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Novo Computador");

        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });

        botao_limpar.setText("Limpar");
        botao_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_limparActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Cancelar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(botao_cadastrar)
                .addGap(141, 141, 141)
                .addComponent(botao_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_cancelar)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cadastrar)
                    .addComponent(botao_limpar)
                    .addComponent(botao_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed
        
        Setor setor = (Setor) cbSetores.getSelectedItem();
        User user = (User) cbUserName.getSelectedItem();

        /*if((cbUserName.getSelectedIndex() == 0) && (cbSetores.getSelectedIndex() == 0)){
            JOptionPane.showMessageDialog(null, "ESCOLHA UM USUÁRIO E UM SETOR PARA CONTINUAR");
        } else if(cbUserName.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "ESCOLHA UM USUÁRIO PARA CONTINUAR");
        } else if(cbSetores.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "ESCOLHA UM SETOR PARA CONTINUAR");
        } else {*/
            Computador computador = new Computador();
            CadastroDAO compDAO = new CadastroDAO();

            computador.setNumTombamento(campo_numTombamento.getText());
            computador.setProcessador(campo_processador.getText());
            computador.setMemoria(campo_memoria.getText() + " GB");
            computador.setHd(campo_hd.getText() + " GB");
            computador.setSsd(cbSsd.isSelected());
            
            
            //JOptionPane.showMessageDialog(null, "USER ID: " + user.getId() + "\nUSER NOME: " + user.getUserNome()
            //                                  + "\nSETOR ID: " + setor.getId() + "\nSETOR NOME: " + setor.getSetorNome());

            compDAO.createComputador(computador);

            campo_hd.setText("");
            campo_processador.setText("");
            campo_memoria.setText("");
            campo_numTombamento.setText("");
            cbUserName.setSelectedIndex(0);
            cbSetores.setSelectedIndex(0);
            cbSsd.setSelected(false);
        //}
    }//GEN-LAST:event_botao_cadastrarActionPerformed

    private void botao_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_limparActionPerformed
        /*campo_nome.setText("");
        campo_telefone.setText("");
        campo_celular.setText("");
        campo_fabricante.setText("");
        campo_produto.setText("");
        campo_codigo.setText("");
        campo_email.setText("");*/
    }//GEN-LAST:event_botao_limparActionPerformed

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void campo_hdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_hdFocusGained
        campo_hd.selectAll();
    }//GEN-LAST:event_campo_hdFocusGained

    private void campo_hdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_hdKeyPressed
        /*if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_telefone.requestFocus();
        }*/
    }//GEN-LAST:event_campo_hdKeyPressed

    private void campo_processadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_processadorFocusGained
        campo_processador.selectAll();
    }//GEN-LAST:event_campo_processadorFocusGained

    private void campo_processadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_processadorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_memoria.requestFocus();
        }
    }//GEN-LAST:event_campo_processadorKeyPressed

    private void campo_memoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_memoriaFocusGained
        campo_memoria.selectAll();
    }//GEN-LAST:event_campo_memoriaFocusGained

    private void campo_memoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_memoriaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_numTombamento.requestFocus();
        }
    }//GEN-LAST:event_campo_memoriaKeyPressed

    private void campo_numTombamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_numTombamentoKeyPressed
        /*if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_email.requestFocus();
        }*/
    }//GEN-LAST:event_campo_numTombamentoKeyPressed

    private void campo_numTombamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_numTombamentoFocusGained
        campo_numTombamento.selectAll();
    }//GEN-LAST:event_campo_numTombamentoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_limpar;
    private javax.swing.JTextField campo_hd;
    private javax.swing.JTextField campo_memoria;
    private javax.swing.JTextField campo_numTombamento;
    private javax.swing.JTextField campo_processador;
    private javax.swing.JComboBox<Object> cbSetores;
    private javax.swing.JCheckBox cbSsd;
    private javax.swing.JComboBox<Object> cbUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_hd;
    private javax.swing.JLabel label_hd1;
    private javax.swing.JLabel label_hd2;
    private javax.swing.JLabel label_memoria;
    private javax.swing.JLabel label_processador;
    private javax.swing.JLabel label_setor;
    private javax.swing.JLabel label_ssd;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_tombamento;
    private javax.swing.JLabel label_usuario;
    // End of variables declaration//GEN-END:variables
}