/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Cadastro;
import Model.DAO.CadastroDAO;
import java.awt.Dimension;

/**
 *
 * @author Leandro Melo
 * 
 * No momento esta tela não se apresenta funcional para o projeto pois está 
 * sendo usada apenas como modelo para as outras telas e aqui ainda existem 
 * alguns itens que podem ser aproveitados futuramente, a exemplo do campo
 * data...
 * 
 */
public class CadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_nome = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        label_produto = new javax.swing.JLabel();
        campo_produto = new javax.swing.JTextField();
        label_data = new javax.swing.JLabel();
        campo_data = new javax.swing.JFormattedTextField();
        label_telefone = new javax.swing.JLabel();
        campo_telefone = new javax.swing.JFormattedTextField();
        label_fabricante = new javax.swing.JLabel();
        campo_fabricante = new javax.swing.JTextField();
        label_celular = new javax.swing.JLabel();
        campo_celular = new javax.swing.JFormattedTextField();
        label_codigo = new javax.swing.JLabel();
        campo_codigo = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        campo_email = new javax.swing.JTextField();
        label_titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botao_cadastrar = new javax.swing.JButton();
        botao_limpar = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CADASTRAR CLIENTE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        label_nome.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_nome.setText("Nome: ");

        campo_nome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campo_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_nomeFocusGained(evt);
            }
        });
        campo_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_nomeKeyPressed(evt);
            }
        });

        label_produto.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_produto.setText("Produto:");

        campo_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_produtoFocusGained(evt);
            }
        });
        campo_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_produtoKeyPressed(evt);
            }
        });

        label_data.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_data.setText("Data de Inclusão:");

        try {
            campo_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_data.setEnabled(false);

        label_telefone.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_telefone.setText("Telefone:");

        try {
            campo_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_telefoneFocusGained(evt);
            }
        });
        campo_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_telefoneKeyPressed(evt);
            }
        });

        label_fabricante.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_fabricante.setText("Fabricante:");

        campo_fabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_fabricanteFocusGained(evt);
            }
        });
        campo_fabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_fabricanteKeyPressed(evt);
            }
        });

        label_celular.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_celular.setText("Celular:");

        try {
            campo_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_celularFocusGained(evt);
            }
        });
        campo_celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_celularKeyPressed(evt);
            }
        });

        label_codigo.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_codigo.setText("Código:");

        campo_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_codigoFocusGained(evt);
            }
        });
        campo_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_codigoKeyPressed(evt);
            }
        });

        label_email.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        label_email.setText("E-mail");

        campo_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_emailFocusGained(evt);
            }
        });
        campo_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_emailKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(campo_produto)
                            .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(campo_email))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_data)
                            .addComponent(campo_data, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nome)
                            .addComponent(label_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_telefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(label_telefone)
                    .addComponent(label_celular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_produto)
                    .addComponent(label_codigo)
                    .addComponent(label_fabricante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_data)
                    .addComponent(label_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_data, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        label_titulo.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Novo Cadastro");

        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });

        botao_limpar.setText("Limpar");
        botao_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_limparActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Fechar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(botao_cadastrar)
                .addGap(212, 212, 212)
                .addComponent(botao_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(botao_cancelar)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cadastrar)
                    .addComponent(botao_limpar)
                    .addComponent(botao_cancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed

        Cadastro cadastro = new Cadastro();
        CadastroDAO cadDAO = new CadastroDAO();

        cadastro.setNOME(campo_nome.getText());
        cadastro.setTELEFONE(campo_telefone.getText());
        cadastro.setCELULAR(campo_celular.getText());
        cadastro.setPRODUTO(campo_produto.getText());
        cadastro.setFABRICANTE(campo_fabricante.getText());
        cadastro.setCODIGO(campo_codigo.getText());
        cadastro.setEMAIL(campo_email.getText());
        cadastro.setDT_INCLUSAO(campo_data.getText());

//        cadDAO.create(cadastro);

        campo_nome.setText("");
        campo_telefone.setText("");
        campo_celular.setText("");
        campo_produto.setText("");
        campo_fabricante.setText("");
        campo_codigo.setText("");
        campo_email.setText("");

    }//GEN-LAST:event_botao_cadastrarActionPerformed

    private void botao_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_limparActionPerformed
        campo_nome.setText("");
        campo_telefone.setText("");
        campo_celular.setText("");
        campo_fabricante.setText("");
        campo_produto.setText("");
        campo_codigo.setText("");
        campo_email.setText("");
    }//GEN-LAST:event_botao_limparActionPerformed

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void campo_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_nomeFocusGained
        campo_nome.selectAll();
    }//GEN-LAST:event_campo_nomeFocusGained

    private void campo_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_nomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_telefone.requestFocus();
        }
    }//GEN-LAST:event_campo_nomeKeyPressed

    private void campo_telefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_telefoneFocusGained
        campo_telefone.selectAll();
    }//GEN-LAST:event_campo_telefoneFocusGained

    private void campo_telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_telefoneKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_celular.requestFocus();
        }
    }//GEN-LAST:event_campo_telefoneKeyPressed

    private void campo_celularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_celularFocusGained
        campo_celular.selectAll();
    }//GEN-LAST:event_campo_celularFocusGained

    private void campo_celularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_celularKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_produto.requestFocus();
        }
    }//GEN-LAST:event_campo_celularKeyPressed

    private void campo_produtoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_produtoFocusGained
        campo_produto.selectAll();
    }//GEN-LAST:event_campo_produtoFocusGained

    private void campo_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_produtoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_fabricante.requestFocus();
        }
    }//GEN-LAST:event_campo_produtoKeyPressed

    private void campo_fabricanteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_fabricanteFocusGained
        campo_fabricante.selectAll();
    }//GEN-LAST:event_campo_fabricanteFocusGained

    private void campo_fabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_fabricanteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_codigo.requestFocus();
        }
    }//GEN-LAST:event_campo_fabricanteKeyPressed

    private void campo_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_codigoFocusGained
        campo_codigo.selectAll();
    }//GEN-LAST:event_campo_codigoFocusGained

    private void campo_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_codigoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_email.requestFocus();
        }
    }//GEN-LAST:event_campo_codigoKeyPressed

    private void campo_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_emailFocusGained
        campo_email.selectAll();
    }//GEN-LAST:event_campo_emailFocusGained

    private void campo_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_emailKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campo_nome.requestFocus();
        }
    }//GEN-LAST:event_campo_emailKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_limpar;
    private javax.swing.JFormattedTextField campo_celular;
    private javax.swing.JTextField campo_codigo;
    public static javax.swing.JFormattedTextField campo_data;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_fabricante;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_produto;
    private javax.swing.JFormattedTextField campo_telefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_celular;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_fabricante;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_produto;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JLabel label_titulo;
    // End of variables declaration//GEN-END:variables
}