/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.Patrimonio;
import Model.Bean.Setor;
import Model.DAO.CadastroDAO;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Melo
 */
public class ConsultaPatrimonio extends javax.swing.JInternalFrame {

    public ConsultaPatrimonio() {
        initComponents();
        readTable();
        
        CadastroDAO setores = new CadastroDAO();

        setores.readSetor().forEach((s) -> {
            cbSetores.addItem(s);
        });
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public static void readTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPatrimonio.getModel();
        modelo.setNumRows(0);

        CadastroDAO.readPatrimonio().forEach((pat) -> {
            modelo.addRow(new Object[]{
                pat.getNumTombamento(),
                pat.getDescricao(),
                pat.getMarca(),
                pat.getObservacao(),
                pat.getSetor().getSetorNome(),
                pat.getComputador().getProcessador(),
                pat.getComputador().getMemoria(),
                pat.getComputador().getHd()
            });
        });
    }

    public void readForTombamento(String numTombamento) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPatrimonio.getModel();
        modelo.setNumRows(0);

        CadastroDAO.readPatrimonio(numTombamento).forEach((pat) -> {
            modelo.addRow(new Object[]{
                pat.getNumTombamento(),
                pat.getDescricao(),
                pat.getMarca(),
                pat.getObservacao(),
                pat.getSetor().getSetorNome(),
                pat.getComputador().getProcessador(),
                pat.getComputador().getMemoria(),
                pat.getComputador().getHd()
            });
        });
    }

    public void readForMarca(String marca) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPatrimonio.getModel();
        modelo.setNumRows(0);

        CadastroDAO.readPatrimonio(marca).forEach((pat) -> {
            modelo.addRow(new Object[]{
                pat.getNumTombamento(),
                pat.getDescricao(),
                pat.getMarca(),
                pat.getObservacao(),
                pat.getSetor().getSetorNome(),
                pat.getComputador().getProcessador(),
                pat.getComputador().getMemoria(),
                pat.getComputador().getHd()
            });
        });
    }

    public void readForSetor(int idSetor) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPatrimonio.getModel();
        modelo.setNumRows(0);
        
        CadastroDAO.readPatrimonio(idSetor).forEach((pat) -> {
            modelo.addRow(new Object[]{
                pat.getNumTombamento(),
                pat.getDescricao(),
                pat.getMarca(),
                pat.getObservacao(),
                pat.getSetor().getSetorNome(),
                pat.getComputador().getProcessador(),
                pat.getComputador().getMemoria(),
                pat.getComputador().getHd()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPatrimonio = new javax.swing.JTable();
        painel5 = new javax.swing.JPanel();
        label_clicad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botao_cancelar = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campo_patrimonio = new javax.swing.JTextField();
        label_patrimonio = new javax.swing.JLabel();
        label_marca = new javax.swing.JLabel();
        campo_marca = new javax.swing.JTextField();
        label_setor = new javax.swing.JLabel();
        campo_ajuda = new javax.swing.JTextField();
        botao_pesMarca = new javax.swing.JButton();
        botao_pesPatrimonio = new javax.swing.JButton();
        cbSetores = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PATRIMÔNIOS CADASTRADOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zoom.png"))); // NOI18N

        tabelaPatrimonio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaPatrimonio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº TOMB", "DESCRIÇÃO", "MARCA", "OBSERVAÇÃO", "SETOR", "PROCESSADOR", "MEMÓRIA", "HD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPatrimonio.setSelectionBackground(new java.awt.Color(52, 156, 174));
        tabelaPatrimonio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPatrimonio.setShowGrid(true);
        jScrollPane1.setViewportView(tabelaPatrimonio);
        if (tabelaPatrimonio.getColumnModel().getColumnCount() > 0) {
            tabelaPatrimonio.getColumnModel().getColumn(0).setMinWidth(70);
            tabelaPatrimonio.getColumnModel().getColumn(0).setPreferredWidth(70);
            tabelaPatrimonio.getColumnModel().getColumn(0).setMaxWidth(70);
            tabelaPatrimonio.getColumnModel().getColumn(1).setMinWidth(350);
            tabelaPatrimonio.getColumnModel().getColumn(1).setPreferredWidth(350);
            tabelaPatrimonio.getColumnModel().getColumn(1).setMaxWidth(350);
            tabelaPatrimonio.getColumnModel().getColumn(2).setMinWidth(90);
            tabelaPatrimonio.getColumnModel().getColumn(2).setPreferredWidth(90);
            tabelaPatrimonio.getColumnModel().getColumn(2).setMaxWidth(90);
            tabelaPatrimonio.getColumnModel().getColumn(3).setMinWidth(220);
            tabelaPatrimonio.getColumnModel().getColumn(3).setPreferredWidth(220);
            tabelaPatrimonio.getColumnModel().getColumn(3).setMaxWidth(220);
            tabelaPatrimonio.getColumnModel().getColumn(4).setMinWidth(100);
            tabelaPatrimonio.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabelaPatrimonio.getColumnModel().getColumn(4).setMaxWidth(100);
            tabelaPatrimonio.getColumnModel().getColumn(5).setMinWidth(190);
            tabelaPatrimonio.getColumnModel().getColumn(5).setPreferredWidth(190);
            tabelaPatrimonio.getColumnModel().getColumn(5).setMaxWidth(190);
            tabelaPatrimonio.getColumnModel().getColumn(6).setMinWidth(75);
            tabelaPatrimonio.getColumnModel().getColumn(6).setPreferredWidth(75);
            tabelaPatrimonio.getColumnModel().getColumn(6).setMaxWidth(75);
            tabelaPatrimonio.getColumnModel().getColumn(7).setMinWidth(70);
            tabelaPatrimonio.getColumnModel().getColumn(7).setPreferredWidth(70);
            tabelaPatrimonio.getColumnModel().getColumn(7).setMaxWidth(70);
        }

        painel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_clicad.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        label_clicad.setForeground(new java.awt.Color(0, 0, 255));
        label_clicad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_clicad.setText("Patrimônios Cadastrados");

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_clicad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_clicad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botao_cancelar.setText("Fechar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(botao_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(botao_alterar)
                .addGap(30, 30, 30)
                .addComponent(botao_excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(botao_cancelar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PESQUISA"));

        campo_patrimonio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campo_patrimonioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campo_patrimonioMouseExited(evt);
            }
        });
        campo_patrimonio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_patrimonioKeyPressed(evt);
            }
        });

        label_patrimonio.setText("PATRIMÔNIO");

        label_marca.setText("MARCA");

        campo_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campo_marcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campo_marcaMouseExited(evt);
            }
        });
        campo_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_marcaKeyPressed(evt);
            }
        });

        label_setor.setText("SETOR");

        campo_ajuda.setEditable(false);
        campo_ajuda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campo_ajuda.setEnabled(false);
        campo_ajuda.setFocusable(false);

        botao_pesMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zoom.png"))); // NOI18N
        botao_pesMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesMarcaActionPerformed(evt);
            }
        });
        botao_pesMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesMarcaKeyPressed(evt);
            }
        });

        botao_pesPatrimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zoom.png"))); // NOI18N
        botao_pesPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesPatrimonioActionPerformed(evt);
            }
        });
        botao_pesPatrimonio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botao_pesPatrimonioKeyPressed(evt);
            }
        });

        cbSetores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLHA UM SETOR" }));
        cbSetores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSetoresItemStateChanged(evt);
            }
        });
        cbSetores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbSetoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbSetoresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_patrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(label_patrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_pesPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(campo_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_pesMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSetores, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo_ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_setor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_marca, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label_patrimonio))
                            .addComponent(label_setor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_patrimonio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_marca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao_pesPatrimonio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(botao_pesMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSetores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(campo_ajuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void botao_pesPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesPatrimonioActionPerformed

        readForTombamento(campo_patrimonio.getText());

    }//GEN-LAST:event_botao_pesPatrimonioActionPerformed

    private void botao_pesMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesMarcaActionPerformed

        readForMarca(campo_marca.getText());

    }//GEN-LAST:event_botao_pesMarcaActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
        if (tabelaPatrimonio.getSelectedRow() != -1) {
            
            AlterarPatrimonio altPatri = new AlterarPatrimonio();
            TelaPrincipal.jDesktopPane.add(altPatri);
            altPatri.setVisible(true);
            altPatri.setPosicao();
            
            Patrimonio patrimonio = new Patrimonio(CadastroDAO.readPatrimonio2(tabelaPatrimonio.getValueAt(tabelaPatrimonio.getSelectedRow(),0).toString()));
            
            AlterarPatrimonio.campo_numTombamento.setText(patrimonio.getNumTombamento());
            AlterarPatrimonio.campo_descricao.setText(patrimonio.getDescricao());
            AlterarPatrimonio.campo_marca.setText(patrimonio.getMarca());
            AlterarPatrimonio.campo_observacao.setText(patrimonio.getObservacao());
            for (int i = 0; i < AlterarPatrimonio.cbSetores.getItemCount(); i++) {
                if (AlterarPatrimonio.cbSetores.getItemAt(i).toString().equals(patrimonio.getSetor().toString())) {
                    AlterarPatrimonio.cbSetores.setSelectedIndex(i);
                } //Função encontrada em: https://www.guj.com.br/t/pegar-todos-os-dados-de-um-jcombobox-resolvido/117110 Usuário: criador. Em: 01/08/2020
            }
            //AlterarPatrimonio.cbPc.setEnabled(false);
            if (patrimonio.getComputador().getId() != 0){
                /*for (int j = 0; j < AlterarPatrimonio.cbUserName.getItemCount(); j++) {
                    if (AlterarPatrimonio.cbUserName.getItemAt(j).toString().equals(patrimonio.getComputador().getUsuario().toString())) {
                        AlterarPatrimonio.cbUserName.setSelectedIndex(j);
                    }//Função encontrada em: https://www.guj.com.br/t/pegar-todos-os-dados-de-um-jcombobox-resolvido/117110 Usuário: criador. Em: 01/08/2020
                }*/
                AlterarPatrimonio.cbPc.setSelected(true);
                AlterarPatrimonio.campo_processador.setText(patrimonio.getComputador().getProcessador());
                AlterarPatrimonio.campo_hd.setText(patrimonio.getComputador().getHd().replaceAll(" GB", ""));
                AlterarPatrimonio.campo_memoria.setText(patrimonio.getComputador().getMemoria().replaceAll(" GB", ""));
                AlterarPatrimonio.cbSsd.setSelected(patrimonio.getComputador().getSsd());
            }
            
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Patrimônio para poder alterar", "ERRO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botao_alterarActionPerformed

    // Ação para o botão excluir, será implantada futuramente..
    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed

        /*AtualizaDAO excCli = new AtualizaDAO();
        excCli.delete(Integer.parseInt(tabelaPatrimonio.getValueAt(tabelaPatrimonio.getSelectedRow(), 0).toString()));*/
        readTable();

    }//GEN-LAST:event_botao_excluirActionPerformed

    private void campo_patrimonioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_patrimonioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && campo_patrimonio.getText().isEmpty()) {
            campo_marca.requestFocus();
            readTable();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && !campo_patrimonio.getText().isEmpty()) {
            readForTombamento(campo_patrimonio.getText());
            campo_patrimonio.selectAll();
        } else if (evt.getKeyCode() == KeyEvent.VK_DELETE && campo_patrimonio.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            readTable();
        }
    }//GEN-LAST:event_campo_patrimonioKeyPressed

    private void botao_pesPatrimonioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesPatrimonioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesPatrimonioKeyPressed

    private void campo_marcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_marcaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && campo_marca.getText().isEmpty()) {
            campo_patrimonio.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && !campo_marca.getText().isEmpty()) {
            readForMarca(campo_marca.getText());
            campo_marca.selectAll();
        } else if (evt.getKeyCode() == KeyEvent.VK_DELETE && campo_marca.getText().isEmpty()) {
            readTable();
        } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            readTable();
        }
    }//GEN-LAST:event_campo_marcaKeyPressed

    private void botao_pesMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botao_pesMarcaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_pesMarcaKeyPressed

    private void campo_patrimonioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_patrimonioMouseEntered
        
        campo_ajuda.setText("Faça uma pesquisa informando um número de tombamento ou parte dele.");
        
    }//GEN-LAST:event_campo_patrimonioMouseEntered

    private void campo_patrimonioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_patrimonioMouseExited
        
        campo_ajuda.setText("");
        
    }//GEN-LAST:event_campo_patrimonioMouseExited

    private void campo_marcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_marcaMouseEntered
        
        campo_ajuda.setText("Faça uma pesquisa informando uma marca ou parte dela.");
        
    }//GEN-LAST:event_campo_marcaMouseEntered

    private void campo_marcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_marcaMouseExited
        
        campo_ajuda.setText("");
        
    }//GEN-LAST:event_campo_marcaMouseExited

    private void cbSetoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSetoresMouseEntered
        
        campo_ajuda.setText("Selecione um setor para pesquisar.");
        
    }//GEN-LAST:event_cbSetoresMouseEntered

    private void cbSetoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSetoresMouseExited
        
        campo_ajuda.setText("");
        
    }//GEN-LAST:event_cbSetoresMouseExited

    private void cbSetoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSetoresItemStateChanged
        if (cbSetores.getSelectedIndex() == 0){
            readTable();
        } else if (cbSetores.getSelectedIndex() == 0) {
            readTable();
        } else {    
            Setor setor = (Setor) cbSetores.getSelectedItem();
            readForSetor(setor.getId());
        }
    }//GEN-LAST:event_cbSetoresItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_pesMarca;
    private javax.swing.JButton botao_pesPatrimonio;
    private javax.swing.JTextField campo_ajuda;
    private javax.swing.JTextField campo_marca;
    private javax.swing.JTextField campo_patrimonio;
    private javax.swing.JComboBox<Object> cbSetores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_clicad;
    private javax.swing.JLabel label_marca;
    private javax.swing.JLabel label_patrimonio;
    private javax.swing.JLabel label_setor;
    private javax.swing.JPanel painel5;
    private static javax.swing.JTable tabelaPatrimonio;
    // End of variables declaration//GEN-END:variables
}
